### ISSUE TITLE
How to reduce react-md-editor size while building?

### ISSUE THREAD

**Issue by rts-gordon** [uiwjs/react-md-editor#531]
Hi there,

  I use react-md-editor in my React app, I found that the app has double size after `npm run build`. Is there any way to reduce the md-editor size while building? Thank you.

Before use react-md-editor: app size: 4.9M, main.xxx.js.map size: 3.8M;
After use react-md-editor: app size: 9.6M, main.xxx.js.map size: 7.3M;

**Comment by jaywcjlove** [comment]
https://github.com/uiwjs/react-md-editor/blob/5db9de2eb6f644da33b4064007ccd8c6f95bfcaa/www/.kktrc.ts#L20-L74

@rts-gordon  You need to do code splitting. Because it supports automatic highlighting of code in multiple programming languages.

https://github.com/uiwjs/react-md-editor/blob/5db9de2eb6f644da33b4064007ccd8c6f95bfcaa/www/package.json#L22

You can use `source-map-explorer` to view your package dependencies

Like thie: https://uiwjs.github.io/react-md-editor/website-result.html

**Comment by rts-gordon** [comment]
Thanks for your answer.

I want to know: why react-md-editor has so huge size after build?

**Comment by jaywcjlove** [comment]
@rts-gordon Because all syntax highlighting is automatically lazy loaded. So all the syntax highlighting code is packed into it.

**Comment by omid** [comment]
@jaywcjlove How to disable it completely if we don't want to use syntax highlighting feature?

**Comment by omid** [comment]
@rts-gordon check out this issue:
https://github.com/uiwjs/react-md-editor/issues/586#issuecomment-1788566091

**Comment by rts-gordon** [comment]
@omid  Thank you. 

I will learn from that issue.
